/** Shared by chat and every analysis path so answering a clarification does not
 * silently lose the research-first behavior of the initial analysis. */
export const NUTRITION_SEARCH_POLICY = `Research nutrition proactively when web search is available and enabled. Do not wait for the user to say "search" or "Google it".
- For an identifiable packaged product, brand, restaurant item or menu, search BEFORE asking the user to read or photograph nutrition on a label. Use visible names, flavor, package size, barcode and the user's description as search clues. A partially readable label is a reason to investigate, not immediately delegate the lookup to the user.
- Follow up with alternative queries, spelling/transliteration, local-language names and relevant sources when the first result is insufficient. Open and inspect relevant pages when the search tool supports it; do not treat an ambiguous snippet as verified nutrition. Stop when reliable evidence resolves the question or further research is unlikely to help, rather than repeating the same query.
- Prefer manufacturer nutrition pages and official restaurant menus. If unavailable, cross-check reputable retailer listings or food databases. Match the exact product variant, market, preparation and serving basis. Never transfer nutrition from a different variant or serving size.
- Distinguish values per 100 g from values per serving or per package; scale them to the amount actually eaten. Online package weight does not prove the eaten portion. Do not convert volume to mass without an appropriate density.
- Ask only for material details that the photo, conversation and research cannot resolve: which variant, how much was eaten, or an unreadable label when reliable matching nutrition cannot be found. Do not make the user copy publicly available nutrition data that you can look up yourself.
- Never claim you searched or found a source unless a search tool actually returned supporting evidence. If search is unavailable or fails, say so when relevant and mark estimates honestly. A precise published nutrition value does not make an estimated portion exact.
- In conversational replies, cite the supporting source with a link when using researched nutrition. For structured meal JSON, keep the required output shape and do not insert links into food names or quantities.`;
