const icon = (name) => {
  const paths = {
    settings: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>',
    camera: '<path d="M14.5 4 16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h3l1.5-3h5Z"/><circle cx="12" cy="13" r="4"/>',
    back: '<path d="m15 18-6-6 6-6"/>', next: '<path d="m9 18 6-6-6-6"/>', close: '<path d="M18 6 6 18M6 6l12 12"/>', check: '<path d="m5 12 4 4L19 6"/>', plus: '<path d="M12 5v14M5 12h14"/>', trash: '<path d="M4 7h16M9 7V4h6v3m3 0-1 14H7L6 7m4 4v6m4-6v6"/>',
    brand: '<path d="M5 12h11a5.5 5.5 0 0 1-11 0Z"/><path d="M7 9h7M8 6h5"/><path d="m15.5 7.5 1.5 1.5 3-3"/>',
    sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.42 1.42m11.3 11.3 1.42 1.42M2 12h2m16 0h2M4.93 19.07l1.42-1.42m11.3-11.3 1.42-1.42"/>',
    fork: '<path d="M7 3v7m-3-7v4a3 3 0 0 0 6 0V3m-3 7v11M17 3v18m0-18c-2 2-3 5-3 8h3"/>', moon: '<path d="M20 15.2A8 8 0 1 1 8.8 4 6.2 6.2 0 0 0 20 15.2Z"/>',
  };
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.fork}</svg>`;
};

const copy = {
  en: {
    today:'Today', yesterday:'Yesterday', kcal:'kcal', kj:'kJ', protein:'Protein', carbs:'Carbs', fat:'Fat', meals:'Meals', logged:'Logged', needsAttention:'Needs attention', needsOneDetail:'Needs one detail', add:'Add meal', noMeals:'No meals yet',
    question:'Question about this meal', questionText:'Was the white sauce sour cream or mayonnaise?', answer:'Type an answer', answerAction:'Answer question', needsInput:'Needs input', estimated:'Estimated', analyzing:'Analyzing', analysisFailed:'Analysis failed', failedHelp:'This meal could not be analyzed.', tryAgain:'Try again', breakfast:'Breakfast', lunch:'Lunch', dinner:'Dinner', snack:'Snack',
    settings:'Settings', details:'Meal', edit:'Edit values', fix:'Describe a correction', correctionHelp:'Use this only when the estimate misunderstood the meal.', correctMeal:'Something wrong? Correct meal', detected:'Detected meal', fixPlaceholder:'Two eggs, not three…', sendCorrection:'Apply correction', correctionApplied:'Correction applied', cameraHint:'Photograph the whole meal', reviewMeal:'Review meal', note:'Add a note (optional)', analyzeMeal:'Analyze meal', send:'Done', addPhoto:'Add photo', removePhoto:'Remove photo', removeHint:'Tap a photo to remove it', captureDetails:'Photos and note', queued:'Meal sent, analyzing in background',
    accountAi:'Account & AI', aiProvider:'AI provider', connected:'OpenAI Codex · Connected', notConnected:'Not connected', providerHelp:'Choose which connected provider analyzes new meals.', connectedProviders:'Connected providers', availableProviders:'Add a provider', selected:'Selected', selectProvider:'Use this provider', addProvider:'Add provider', prototypeProvider:'Prototype connection only', model:'Model', automatic:'Automatic', disconnect:'Disconnect', connect:'Connect',
    tracking:'Tracking', goals:'Daily goals', goalsHelp:'A quiet reference only. CalDone never grades your food.', calories:'Calories', units:'Nutrition units', metricUnits:'kcal · grams', notifications:'Notifications', questionsFailures:'Questions and failures', save:'Save', appSection:'App', language:'Language', dataPrivacy:'Data & privacy', savedPhotos:'Photos kept with meals', about:'About CalDone', version:'Version 1.0.0',
    notificationHelp:'Choose when CalDone is allowed to interrupt you.', clarificationNotifications:'Meal questions', clarificationNotificationsHelp:'When an answer could materially change the estimate', failedNotifications:'Failed analysis', failedNotificationsHelp:'When a meal could not be processed', readyNotifications:'Meal ready', readyNotificationsHelp:'After every successful analysis', reminderNotifications:'Daily reminder', reminderNotificationsHelp:'A quiet prompt if no meals were logged', done:'Done',
    energy:'Energy', portionWeight:'Portion weight', grams:'Grams', ounces:'Ounces', unitHelp:'These units change how nutrition is displayed. Stored values keep their precision.', privacyHelp:'Meal photos stay in private app storage and never enter the system gallery.', photoStorage:'Meal photos', privateStorage:'Saved with each meal', systemGallery:'System gallery', never:'Never', includeExport:'Include photos in export', exportData:'Export my data', removePhotos:'Remove all saved photos', deleteData:'Delete all meal data', confirmRemovePhotos:'Remove photos from every meal?', confirmDeleteData:'Delete every meal and photo?', cancel:'Cancel', delete:'Delete', exported:'Mock export downloaded', photosRemoved:'Saved photos removed', dataDeleted:'Meal data deleted',
    aboutBody:'A quiet calorie tracker for people who do not want tracking to become another job.', openSource:'Open source prototype', license:'Prototype UI · MIT licensed project', editMeal:'Edit meal', mealType:'Meal type', title:'Title', time:'Time', items:'Items', itemName:'Food', quantity:'Quantity', addItem:'Add item', saveChanges:'Save changes', deleteMeal:'Delete meal', confirmDeleteMeal:'Delete this meal?', changesSaved:'Meal updated', mealPhotos:'Meal photos', photo:'photo', photos:'photos', photoSaved:'saved photo', photosSaved:'saved photos', yourNote:'Your note', openPhoto:'Open photo', removeSelected:'Remove selected photo', back:'Back', takePhoto:'Take photo', usePhoto:'Use photo', usePhotos:'Use photos', previousDay:'Previous day', nextDay:'Next day', close:'Close', typeAnswer:'Type an answer first', typeCorrection:'Describe the correction first', setupGoal:'What are you working toward?', lose:'Lose weight', maintain:'Maintain weight', gain:'Gain weight', setupBasics:'Tell us about you', age:'Age', height:'Height', weight:'Weight', equationSex:'Sex used by the equation', female:'Female', male:'Male', equationHelp:'Used only to estimate resting energy needs.', setupActivity:'How active are most weeks?', sedentary:'Mostly seated', light:'Lightly active', moderate:'Moderately active', veryActive:'Very active', setupTargets:'Your starting targets', targetsHelp:'An editable estimate, not medical advice.', setupProvider:'Choose your AI provider', providerSetupHelp:'You can add or switch providers later in Settings.', continue:'Continue', finishSetup:'Finish setup', stepOf:'Step {{step}} of 5'
  },
  ru: {
    today:'Сегодня', yesterday:'Вчера', kcal:'ккал', kj:'кДж', protein:'Белки', carbs:'Углеводы', fat:'Жиры', meals:'Приёмы пищи', logged:'Записано', needsAttention:'Требует внимания', needsOneDetail:'Нужно уточнение', add:'Добавить еду', noMeals:'Пока ничего нет', question:'Вопрос об этой еде', questionText:'Белый соус: сметана или майонез?', answer:'Написать ответ', answerAction:'Ответить на вопрос', needsInput:'Нужен ответ', estimated:'Оценено', analyzing:'Анализируем', analysisFailed:'Ошибка анализа', failedHelp:'Не удалось проанализировать этот приём пищи.', tryAgain:'Повторить', breakfast:'Завтрак', lunch:'Обед', dinner:'Ужин', snack:'Перекус',
    settings:'Настройки', details:'Еда', edit:'Изменить значения', fix:'Опишите исправление', correctionHelp:'Используйте, только если оценка неверно поняла еду.', correctMeal:'Что-то не так? Исправить', detected:'Распознанная еда', fixPlaceholder:'Два яйца, не три…', sendCorrection:'Применить исправление', correctionApplied:'Исправление применено', cameraHint:'Снимите весь приём пищи', reviewMeal:'Проверка фото', note:'Добавить заметку (необязательно)', analyzeMeal:'Анализировать еду', send:'Готово', addPhoto:'Добавить фото', removePhoto:'Удалить фото', removeHint:'Нажмите фото, чтобы удалить', captureDetails:'Фото и заметка', queued:'Еда отправлена, анализируем в фоне',
    accountAi:'Аккаунт и ИИ', aiProvider:'ИИ-провайдер', connected:'OpenAI Codex · Подключён', notConnected:'Не подключён', providerHelp:'Выберите, какой подключённый провайдер анализирует новые блюда.', connectedProviders:'Подключённые провайдеры', availableProviders:'Добавить провайдера', selected:'Выбран', selectProvider:'Использовать', addProvider:'Добавить провайдера', prototypeProvider:'Только прототип подключения', model:'Модель', automatic:'Автоматически', disconnect:'Отключить', connect:'Подключить', tracking:'Отслеживание', goals:'Дневные цели', goalsHelp:'Только спокойный ориентир. CalDone не оценивает вашу еду.', calories:'Калории', units:'Единицы измерения', metricUnits:'ккал · граммы', notifications:'Уведомления', questionsFailures:'Вопросы и ошибки', save:'Сохранить', appSection:'Приложение', language:'Язык', dataPrivacy:'Данные и приватность', savedPhotos:'Фото хранятся вместе с едой', about:'О CalDone', version:'Версия 1.0.0',
    notificationHelp:'Выберите, когда CalDone может вас отвлекать.', clarificationNotifications:'Вопросы о еде', clarificationNotificationsHelp:'Когда ответ может заметно изменить оценку', failedNotifications:'Ошибка анализа', failedNotificationsHelp:'Если еду не удалось обработать', readyNotifications:'Еда готова', readyNotificationsHelp:'После каждого успешного анализа', reminderNotifications:'Ежедневное напоминание', reminderNotificationsHelp:'Если за день ничего не добавлено', done:'Готово',
    energy:'Энергия', portionWeight:'Вес порций', grams:'Граммы', ounces:'Унции', unitHelp:'Единицы меняют только отображение. Сохранённые значения не теряют точность.', privacyHelp:'Фото еды хранятся внутри приложения и не попадают в системную галерею.', photoStorage:'Фотографии еды', privateStorage:'Сохранены вместе с едой', systemGallery:'Системная галерея', never:'Никогда', includeExport:'Добавлять фото в экспорт', exportData:'Экспортировать мои данные', removePhotos:'Удалить все сохранённые фото', deleteData:'Удалить всю историю еды', confirmRemovePhotos:'Удалить фотографии из всех приёмов пищи?', confirmDeleteData:'Удалить всю еду и фотографии?', cancel:'Отмена', delete:'Удалить', exported:'Тестовый экспорт скачан', photosRemoved:'Сохранённые фото удалены', dataDeleted:'История еды удалена',
    aboutBody:'Спокойный счётчик калорий для тех, кто не хочет превращать учёт еды в отдельную работу.', openSource:'Открытый прототип', license:'Прототип интерфейса · проект MIT', editMeal:'Изменить еду', mealType:'Тип еды', title:'Название', time:'Время', items:'Состав', itemName:'Продукт', quantity:'Количество', addItem:'Добавить продукт', saveChanges:'Сохранить изменения', deleteMeal:'Удалить приём пищи', confirmDeleteMeal:'Удалить этот приём пищи?', changesSaved:'Еда обновлена', mealPhotos:'Фотографии еды', photo:'фото', photos:'фото', photoSaved:'сохранённое фото', photosSaved:'сохранённых фото', yourNote:'Ваша заметка', openPhoto:'Открыть фото', removeSelected:'Удалить выбранное фото', back:'Назад', takePhoto:'Сделать фото', usePhoto:'Использовать фото', usePhotos:'Использовать фото', previousDay:'Предыдущий день', nextDay:'Следующий день', close:'Закрыть', typeAnswer:'Сначала напишите ответ', typeCorrection:'Сначала опишите исправление', setupGoal:'К какой цели вы идёте?', lose:'Снизить вес', maintain:'Сохранить вес', gain:'Набрать вес', setupBasics:'Расскажите о себе', age:'Возраст', height:'Рост', weight:'Вес', equationSex:'Пол для формулы', female:'Женский', male:'Мужской', equationHelp:'Используется только для оценки энергозатрат в покое.', setupActivity:'Насколько вы активны?', sedentary:'В основном сижу', light:'Лёгкая активность', moderate:'Средняя активность', veryActive:'Высокая активность', setupTargets:'Ваши стартовые цели', targetsHelp:'Редактируемая оценка, а не медицинская рекомендация.', setupProvider:'Выберите ИИ-провайдера', providerSetupHelp:'Добавить или сменить провайдера можно позже в настройках.', continue:'Продолжить', finishSetup:'Завершить настройку', stepOf:'Шаг {{step}} из 5'
  }
};

const makeItem=(nameEn,nameRu,quantity,calories,protein,carbs,fat)=>({nameEn,nameRu,quantity,calories,protein,carbs,fat});
const initialMeals=[
  {id:'breakfast',day:0,type:'breakfast',time:'08:20',titleEn:'Oatmeal with berries',titleRu:'Овсянка с ягодами',photoCount:2,photoAssets:['images/oatmeal-berries.webp','images/oatmeal-berries-closeup.webp'],note:'Oat milk, no added sugar.',status:'estimated',items:[makeItem('Oatmeal','Овсянка','220 g',280,10,48,6),makeItem('Blueberries','Черника','70 g',40,1,9,0),makeItem('Yogurt','Йогурт','120 g',118,8,12,4)]},
  {id:'lunch',day:0,type:'lunch',time:'13:05',titleEn:'Chicken, buckwheat & salad',titleRu:'Курица с гречкой и салатом',photoCount:1,status:'needs_input',question:true,items:[makeItem('Chicken breast','Куриная грудка','170 g',280,38,0,12),makeItem('Buckwheat','Гречка','180 g',198,7,38,2),makeItem('Cucumber salad','Салат из огурцов','150 g',74,2,8,4),makeItem('Sour cream','Сметана','30 g',60,1,2,5)]},
  {id:'dinner',day:0,type:'dinner',time:'19:18',titleEn:'Toast, eggs & avocado',titleRu:'Тост, яйца и авокадо',photoCount:0,status:'estimated',items:[makeItem('Eggs','Яйца','2',144,13,1,10),makeItem('Toast','Тост','1 slice',72,3,13,1),makeItem('Avocado','Авокадо','40 g',60,1,3,5)]},
  {id:'past-lunch',day:-1,type:'lunch',time:'12:44',titleEn:'Tomato pasta',titleRu:'Паста с томатами',photoCount:1,status:'estimated',items:[makeItem('Pasta','Паста','280 g',510,16,82,12)]},
  {id:'past-dinner',day:-1,type:'dinner',time:'20:03',titleEn:'Cottage cheese & apple',titleRu:'Творог и яблоко',photoCount:1,status:'estimated',items:[makeItem('Cottage cheese','Творог','200 g',242,32,7,9),makeItem('Apple','Яблоко','1',80,0,21,0)]}
];

const state={screen:localStorage.getItem('calodone-guide-seen')==='true'?'home':'onboarding',transition:'none',onboardingStep:0,setup:{goal:'maintain',age:'30',height:'170',weight:'70',sex:'female',activity:'moderate',calories:2000,protein:120,carbs:220,fat:65,provider:'codex'},lang:'en',toast:'',day:0,selectedMealId:'lunch',photos:0,addingAngle:false,selectedPhoto:0,photoViewer:'',note:'',connected:true,connectedProviders:['codex'],selectedProvider:'codex',showProviderCatalog:false,showCorrection:false,units:{energy:'kcal',weight:'g'},goals:{calories:2000,protein:120,carbs:220,fat:65},goalDraft:null,editDraft:null,exportPhotos:true,notifications:{questions:true,failed:true,ready:false,reminder:false},meals:structuredClone(initialMeals),confirm:'',correction:'',answerText:''};
const t=key=>copy[state.lang][key]??key;
const app=document.querySelector('#app');
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const energy=kcal=>state.units.energy==='kj'?Math.round(kcal*4.184):Math.round(kcal);
const energyUnit=()=>t(state.units.energy==='kj'?'kj':'kcal');
const itemName=item=>item.customName??(state.lang==='ru'?item.nameRu:item.nameEn);
const mealTitle=meal=>meal.customTitle??(state.lang==='ru'?meal.titleRu:meal.titleEn);
const totals=meal=>meal.items.reduce((sum,item)=>({calories:sum.calories+Number(item.calories),protein:sum.protein+Number(item.protein),carbs:sum.carbs+Number(item.carbs),fat:sum.fat+Number(item.fat)}),{calories:0,protein:0,carbs:0,fat:0});
const selectedMeal=()=>state.meals.find(meal=>meal.id===state.selectedMealId);
function shell(content,extra=''){const viewer=state.photoViewer?`<div class="photo-viewer" role="dialog" aria-label="${t('mealPhotos')}"><button class="icon-btn" data-action="close-photo" aria-label="${t('close')}">${icon('close')}</button><img src="${state.photoViewer}" alt=""></div>`:'';return `<div class="device ${extra} transition-${state.transition}">${content}${viewer}${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}</div>`;}
function btnIcon(name,label,action,disabled=false){return `<button class="icon-btn" aria-label="${esc(label)}" data-action="${action}" ${disabled?'disabled':''}>${icon(name)}</button>`;}
function foodPlate(){return '<i class="tiny-plate"><i class="tiny-food one"></i><i class="tiny-food two"></i><i class="tiny-food three"></i></i>';}
function header(title,back,action=''){return `<header class="header">${btnIcon('back',t('back'),back)}<h2>${esc(title)}</h2>${action||'<span></span>'}</header>`;}

function onboarding(){const step=state.onboardingStep;const titles=[t('setupGoal'),t('setupBasics'),t('setupActivity'),t('setupTargets'),t('setupProvider')];const body=step===0?choiceCards('goal',[['lose',t('lose')],['maintain',t('maintain')],['gain',t('gain')]]):step===1?basicsSetup():step===2?choiceCards('activity',[['sedentary',t('sedentary')],['light',t('light')],['moderate',t('moderate')],['veryActive',t('veryActive')]]):step===3?targetsSetup():providerSetup();return shell(`<section class="onboarding setup-onboarding"><header class="setup-head">${step?btnIcon('back',t('back'),'setup-back'):'<span></span>'}<span>${t('stepOf').replace('{{step}}',step+1)}</span></header><div class="setup-title"><h1>${titles[step]}</h1>${step===3?`<p>${t('targetsHelp')}</p>`:step===4?`<p>${t('providerSetupHelp')}</p>`:''}</div><div class="setup-body">${body}</div><button class="primary" data-action="${step===4?'finish-setup':'setup-next'}">${t(step===4?'finishSetup':'continue')}</button></section>`);}
function choiceCards(field,options){return `<div class="setup-choices">${options.map(([value,label])=>`<button class="setup-choice ${state.setup[field]===value?'selected':''}" data-action="setup-choice" data-field="${field}" data-value="${value}"><span>${label}</span>${state.setup[field]===value?icon('check'):''}</button>`).join('')}</div>`;}
function basicsSetup(){return `<div class="setup-fields"><label><span>${t('age')}</span><input inputmode="numeric" data-setup="age" value="${state.setup.age}"></label><label><span>${t('height')}</span><div><input inputmode="decimal" data-setup="height" value="${state.setup.height}"><b>cm</b></div></label><label><span>${t('weight')}</span><div><input inputmode="decimal" data-setup="weight" value="${state.setup.weight}"><b>kg</b></div></label></div><div class="equation-choice"><span>${t('equationSex')}</span>${choiceCards('sex',[['female',t('female')],['male',t('male')]])}<small>${t('equationHelp')}</small></div>`;}
function targetsSetup(){return `<div class="target-fields"><label><span>${t('calories')}</span><div><input inputmode="decimal" data-setup="calories" value="${state.setup.calories}"><b>${t('kcal')}</b></div></label><label><span>${t('protein')}</span><div><input inputmode="decimal" data-setup="protein" value="${state.setup.protein}"><b>g</b></div></label><label><span>${t('carbs')}</span><div><input inputmode="decimal" data-setup="carbs" value="${state.setup.carbs}"><b>g</b></div></label><label><span>${t('fat')}</span><div><input inputmode="decimal" data-setup="fat" value="${state.setup.fat}"><b>g</b></div></label></div>`;}
function providerSetup(){return choiceCards('provider',[['codex','OpenAI Codex'],['openai-api','OpenAI API'],['anthropic','Anthropic']]);}
function calculateTargets(){const s=state.setup;const age=Math.max(18,Number(s.age)||30);const height=Math.max(120,Number(s.height)||170);const weight=Math.max(35,Number(s.weight)||70);const base=10*weight+6.25*height-5*age+(s.sex==='male'?5:-161);const factors={sedentary:1.2,light:1.375,moderate:1.55,veryActive:1.725};const adjustment=s.goal==='lose'?-300:s.goal==='gain'?250:0;const calories=Math.max(1200,Math.round((base*factors[s.activity]+adjustment)/50)*50);const protein=Math.round(weight*1.6/5)*5;const fat=Math.round((calories*.25/9)/5)*5;const carbs=Math.max(0,Math.round(((calories-protein*4-fat*9)/4)/5)*5);Object.assign(s,{calories,protein,fat,carbs});}

function home(){
  const meals=state.meals.filter(meal=>meal.day===state.day);const sum=meals.reduce((total,meal)=>{const value=totals(meal);Object.keys(total).forEach(k=>total[k]+=value[k]);return total;},{calories:0,protein:0,carbs:0,fat:0});const newest=(a,b)=>b.time.localeCompare(a.time);const attention=meals.filter(meal=>meal.question||meal.status==='failed').sort(newest);const processing=meals.filter(meal=>meal.status==='queued').sort(newest);const completed=meals.filter(meal=>!attention.includes(meal)&&!processing.includes(meal)).sort(newest);const lead=attention[0];const dayTitle=state.day===0?t('today'):t('yesterday');const leadBlock=lead?(lead.question?clarification(lead,true):failureAction(lead)):'';const additionalAttention=attention.slice(1);const attentionBlock=additionalAttention.length?`<div class="meal-list required-list">${additionalAttention.map(requiredRow).join('')}</div>`:'';const processingBlock=processing.length?`<div class="meal-list active-list">${processing.map(mealRow).join('')}</div>`:'';const history=completed.length?completed.map(mealRow).join(''):(meals.length?'':`<p class="empty-line">${t('noMeals')}</p>`);
  return shell(`<section class="screen home-screen"><header class="topbar simple-topbar">${btnIcon('back',t('previousDay'),'past',state.day<0)}<h1>${dayTitle}</h1>${btnIcon('next',t('nextDay'),'today',state.day===0)}${btnIcon('settings',t('settings'),'settings')}</header>${leadBlock}${attentionBlock}${processingBlock}<section class="summary compact-summary"><p class="calories">${energy(sum.calories).toLocaleString()} <span class="unit">/ ${energy(state.goals.calories).toLocaleString()} ${energyUnit()}</span></p><p class="macro-inline">P ${Math.round(sum.protein)} · C ${Math.round(sum.carbs)} · F ${Math.round(sum.fat)}</p></section><div class="meal-list quiet-list">${history}</div><div class="capture-dock"><button class="primary" data-action="new-capture">${icon('camera')} ${t('add')}</button></div></section>`);
}
function macro(value,goal,label){const shown=state.units.weight==='oz'?(value/28.35).toFixed(1):Math.round(value);const goalShown=state.units.weight==='oz'?(goal/28.35).toFixed(1):goal;return `<div class="macro"><strong>${shown} / ${goalShown} ${state.units.weight==='oz'?'oz':'g'}</strong><small>${label}</small></div>`;}
function clarification(meal,withLink){return `<section class="question primary-question">${withLink?`<button class="question-meal" data-action="open-meal" data-meal-id="${meal.id}"><img class="mini-photo" src="${mealImage(meal)}" alt=""><span><strong>${t(meal.type)} · ${meal.time}</strong><small>${t('needsOneDetail')}</small></span><b aria-hidden="true">${icon('next')}</b></button>`:''}<p class="question-text">${t('questionText')}</p><div class="composer"><input data-bind="answer" value="${esc(state.answerText)}" placeholder="${t('answer')}"/><button class="send-circle" data-action="answer" aria-label="${t('answerAction')}">${icon('check')}</button></div></section>`;}
function failureAction(meal){return `<section class="question primary-question failure-question"><button class="question-meal" data-action="open-meal" data-meal-id="${meal.id}"><img class="mini-photo" src="${mealImage(meal)}" alt=""><span><strong>${esc(mealTitle(meal))}</strong><small>${meal.time}</small></span><b aria-hidden="true">${icon('next')}</b></button><p class="question-text">${t('analysisFailed')}</p><p class="fix-help">${t('failedHelp')}</p><button class="retry-action" data-action="retry-analysis" data-meal-id="${meal.id}">${t('tryAgain')}</button></section>`;}
function requiredRow(meal){const failed=meal.status==='failed';return `<button class="meal quiet-meal required-meal ${failed?'failed':''}" data-action="open-meal" data-meal-id="${meal.id}"><img class="meal-thumb" src="${mealImage(meal)}" alt=""><span class="meal-copy"><span class="meal-title">${esc(mealTitle(meal))}</span><span class="meal-meta"><span>${meal.time}</span><span class="required-status">${t(failed?'analysisFailed':'needsOneDetail')}</span></span></span>${icon('next')}</button>`;}
function mealRow(meal){const total=totals(meal);const queued=meal.status==='queued';const visual=meal.photoCount?`<span class="meal-thumb-wrap"><img class="meal-thumb" src="${mealImage(meal)}" alt="">${queued?'<i class="analysis-pulse"></i>':''}</span>`:'';const value=queued?`<span class="analysis-status"><i class="dot"></i>${t('analyzing')}</span>`:`<span>${energy(total.calories)} ${energyUnit()}</span>`;return `<button class="meal quiet-meal ${meal.photoCount?'':'without-photo'} ${queued?'processing-meal':''}" data-action="open-meal" data-meal-id="${meal.id}">${visual}<span class="meal-copy"><span class="meal-title">${esc(mealTitle(meal))}</span><span class="meal-meta"><span>${meal.time}</span>${value}</span></span>${icon('next')}</button>`;}

function detail(){
  const meal=selectedMeal();if(!meal)return home();const total=totals(meal);
  if(meal.status==='queued')return shell(`<section class="screen detail">${header(t('details'),'home')}<p class="meal-type">${t(meal.type)} · ${meal.time}</p><h1 class="detail-title">${esc(mealTitle(meal))}</h1>${photoBlock(meal)}<section class="processing"><i class="dot"></i><strong>${t('analyzing')}</strong><p>${esc(meal.note)}</p></section></section>`);
  return shell(`<section class="screen detail">${header(t('details'),'home')}<div class="review-heading"><small>${t(meal.type)} · ${meal.time}</small><button class="header-action" data-action="edit">${t('edit')}</button></div><h1 class="detail-title">${esc(mealTitle(meal))}</h1>${photoBlock(meal)}${meal.note?`<p class="meal-note"><span>${t('yourNote')}</span>${esc(meal.note)}</p>`:''}${meal.question?clarification(meal,false):''}<div class="detail-total"><strong>${energy(total.calories)} ${energyUnit()}</strong><span>P ${Math.round(total.protein)} · C ${Math.round(total.carbs)} · F ${Math.round(total.fat)}</span></div><div>${meal.items.map(item=>`<div class="food-row"><div><strong>${esc(itemName(item))}</strong><small>${esc(item.quantity)}</small></div><div class="food-nutrition"><strong>${energy(item.calories)} ${energyUnit()}</strong><small>P ${item.protein} · C ${item.carbs} · F ${item.fat}</small></div></div>`).join('')}</div>${meal.correction?`<p class="applied-correction">${t('correctionApplied')}: ${esc(meal.correction)}</p>`:''}<button class="secondary-action" data-action="toggle-correction">${t('correctMeal')}</button>${state.showCorrection?correctionBlock():''}</section>`);
}
function correctionBlock(){return `<section class="ai-fix"><p class="ai-label">${t('fix')}</p><p class="fix-help">${t('correctionHelp')}</p><div class="composer"><input data-bind="correction" value="${esc(state.correction)}" placeholder="${t('fixPlaceholder')}"/><button class="send-circle" data-action="fix" aria-label="${t('sendCorrection')}">${icon('check')}</button></div></section>`;}
function mealImages(meal){if(meal.photoAssets?.length)return meal.photoAssets;const images={breakfast:'images/oatmeal-berries.webp',lunch:'images/chicken-buckwheat-salad.webp',dinner:'images/toast-eggs-avocado.webp'};return [images[meal.id]||images[meal.type]||'images/chicken-buckwheat-salad.webp'];}
function mealImage(meal){return mealImages(meal)[0];}
function photoBlock(meal){if(!meal.photoCount)return '';const photos=mealImages(meal).slice(0,meal.photoCount);return `<section class="saved-photos photo-grid ${photos.length>1?'multiple':''}" aria-label="${t('mealPhotos')}">${photos.map((src,index)=>`<button class="saved-photo" data-action="open-photo" data-src="${src}" aria-label="${t('openPhoto')} ${index+1} / ${photos.length}"><img src="${src}" alt=""><span>${index+1} / ${photos.length}</span></button>`).join('')}</section>`;}

function settings(){return shell(`<section class="screen settings">${header(t('settings'),'home')}${settingsSection(t('accountAi'),settingsLink(t('aiProvider'),state.connected?t('connected'):t('notConnected'),'provider'))}${settingsSection(t('tracking'),settingsLink(t('goals'),`${state.goals.calories} ${t('kcal')}`,'goals')+settingsLink(t('units'),`${energyUnit()} · ${state.units.weight==='oz'?t('ounces').toLowerCase():t('grams').toLowerCase()}`,'units')+settingsLink(t('notifications'),t('questionsFailures'),'notifications'))}${settingsSection(t('appSection'),settingsLink(t('language'),state.lang==='en'?'English':'Русский','language')+settingsLink(t('dataPrivacy'),t('savedPhotos'),'privacy')+settingsLink(t('about'),t('version'),'about'))}</section>`);}
function settingsSection(title,content){return `<section class="settings-section"><h3>${title}</h3><div class="settings-panel">${content}</div></section>`;}
function settingsLink(label,value,action){return `<button class="settings-link" data-action="${action}"><span><strong>${label}</strong><small>${value}</small></span><b aria-hidden="true">${icon('next')}</b></button>`;}
function infoRow(label,value){return `<div class="info-row"><span>${label}</span><strong>${value}</strong></div>`;}
function provider(){const connected=state.connectedProviders.map(id=>providerRow(id,id==='codex'?'OpenAI Codex':id==='openai-api'?'OpenAI API':'Anthropic',true)).join('');const catalog=state.showProviderCatalog?`<section class="provider-catalog"><h3>${t('availableProviders')}</h3>${providerRow('openai-api','OpenAI API',false)}${providerRow('anthropic','Anthropic',false)}<small>${t('prototypeProvider')}</small></section>`:'';return shell(`<section class="screen settings">${header(t('aiProvider'),'settings')}<p class="settings-copy detail-copy">${t('providerHelp')}</p><h3 class="provider-heading">${t('connectedProviders')}</h3><div class="provider-list">${connected}</div><button class="secondary-action" data-action="toggle-provider-catalog">${t('addProvider')}</button>${catalog}</section>`);}
function providerRow(id,name,connected){const selected=state.selectedProvider===id;return `<button class="provider-row ${selected?'selected':''}" data-action="${connected?'select-provider':'connect-provider'}" data-provider="${id}" aria-pressed="${selected}"><span class="provider-radio">${selected?icon('check'):''}</span><strong>${name}</strong>${connected?'':`<span class="provider-add">${t('connect')}</span>`}</button>`;}
function goals(){return shell(`<section class="screen settings">${header(t('goals'),'settings')}<p class="settings-copy detail-copy">${t('goalsHelp')}</p><div class="settings-panel goal-panel">${goalField('calories',t('calories'),t('kcal'))}${goalField('protein',t('protein'),'g')}${goalField('carbs',t('carbs'),'g')}${goalField('fat',t('fat'),'g')}</div><div class="settings-primary"><button class="primary" data-action="save-goals">${t('save')}</button></div></section>`);}
function goalField(key,label,unit){const values=state.goalDraft??state.goals;return `<label class="setting-row"><span>${label}</span><span class="number-input"><input inputmode="decimal" data-goal="${key}" value="${values[key]}"><b>${unit}</b></span></label>`;}
function notifications(){return shell(`<section class="screen settings">${header(t('notifications'),'settings')}<p class="settings-copy detail-copy">${t('notificationHelp')}</p><div class="settings-panel notification-panel">${toggleSetting('questions',t('clarificationNotifications'),t('clarificationNotificationsHelp'))}${toggleSetting('failed',t('failedNotifications'),t('failedNotificationsHelp'))}${toggleSetting('ready',t('readyNotifications'),t('readyNotificationsHelp'))}${toggleSetting('reminder',t('reminderNotifications'),t('reminderNotificationsHelp'))}</div></section>`);}
function toggleSetting(key,label,help){const checked=state.notifications[key];return `<div class="toggle-row"><span><strong>${label}</strong><small>${help}</small></span><button class="toggle ${checked?'checked':''}" role="switch" aria-checked="${checked}" aria-label="${label}" data-action="toggle-notification" data-key="${key}"><i></i></button></div>`;}
function units(){return shell(`<section class="screen settings">${header(t('units'),'settings')}<p class="settings-copy detail-copy">${t('unitHelp')}</p>${choiceGroup(t('energy'),'energy',[['kcal',t('kcal')],['kj',t('kj')]],state.units.energy)}${choiceGroup(t('portionWeight'),'weight',[['g',t('grams')],['oz',t('ounces')]],state.units.weight)}</section>`);}
function choiceGroup(title,key,options,current){return `<section class="choice-section"><h3>${title}</h3><div class="choice-control">${options.map(([value,label])=>`<button data-action="choose-unit" data-key="${key}" data-value="${value}" class="${current===value?'selected':''}" aria-pressed="${current===value}">${label}</button>`).join('')}</div></section>`;}
function privacy(){return shell(`<section class="screen settings">${header(t('dataPrivacy'),'settings')}<p class="settings-copy detail-copy">${t('privacyHelp')}</p><div class="settings-panel"><div class="toggle-row privacy-toggle"><span><strong>${t('includeExport')}</strong></span><button class="toggle ${state.exportPhotos?'checked':''}" role="switch" aria-checked="${state.exportPhotos}" aria-label="${t('includeExport')}" data-action="toggle-export"><i></i></button></div></div><div class="action-list"><button data-action="export-data">${t('exportData')}</button><button data-action="confirm-remove-photos">${t('removePhotos')}</button><button class="danger-text" data-action="confirm-delete-data">${t('deleteData')}</button></div>${confirmPanel()}</section>`);}
function confirmPanel(){if(!state.confirm)return '';const removing=state.confirm==='photos';return `<section class="confirm-panel"><strong>${t(removing?'confirmRemovePhotos':'confirmDeleteData')}</strong><div><button data-action="cancel-confirm">${t('cancel')}</button><button class="danger-fill" data-action="${removing?'remove-photos':'delete-data'}">${t('delete')}</button></div></section>`;}
function about(){return shell(`<section class="screen settings">${header(t('about'),'settings')}<div class="about-mark">${icon('brand')}</div><h1 class="about-title">CalDone</h1><p class="about-copy">${t('aboutBody')}</p><div class="settings-panel about-info">${infoRow(t('version'),'1.0.0')}${infoRow(t('openSource'),'CalDone')}${infoRow('License','MIT')}</div><p class="about-foot">${t('license')}</p></section>`);}

function editor(){const meal=state.editDraft;if(!meal)return detail();return shell(`<section class="screen settings editor">${header(t('details'),'detail')}<div class="review-heading"><div><h2>${t('detected')}</h2><small>${t(meal.type)} · ${meal.time}</small></div><button class="header-action" data-action="detail">${t('cancel')}</button></div><label class="editor-field"><span>${t('mealType')}</span><div class="type-chips">${['breakfast','lunch','dinner','snack'].map(type=>`<button data-action="set-meal-type" data-value="${type}" class="${meal.type===type?'selected':''}">${t(type)}</button>`).join('')}</div></label><div class="editor-top"><label class="editor-field"><span>${t('title')}</span><input data-meal-field="customTitle" value="${esc(mealTitle(meal))}"></label><label class="editor-field compact"><span>${t('time')}</span><input data-meal-field="time" value="${meal.time}"></label></div><h3 class="editor-heading">${t('items')}</h3><div class="editor-items">${meal.items.map((item,index)=>editorItem(item,index,meal.items.length>1)).join('')}</div><button class="add-item" data-action="add-item">＋ ${t('addItem')}</button><div class="settings-primary"><button class="primary" data-action="save-meal">${t('saveChanges')}</button></div><button class="text-action danger-text" data-action="confirm-delete-meal">${t('deleteMeal')}</button>${state.confirm==='meal'?`<section class="confirm-panel"><strong>${t('confirmDeleteMeal')}</strong><div><button data-action="cancel-confirm">${t('cancel')}</button><button class="danger-fill" data-action="delete-meal">${t('delete')}</button></div></section>`:''}</section>`);}
function editorItem(item,index,canRemove){return `<section class="item-editor"><div class="item-editor-head"><strong>${index+1}</strong>${canRemove?`<button aria-label="Remove item" data-action="remove-item" data-index="${index}">×</button>`:''}</div><div class="editor-top"><label class="editor-field"><span>${t('itemName')}</span><input data-item="${index}" data-item-field="customName" value="${esc(itemName(item))}"></label><label class="editor-field compact"><span>${t('quantity')}</span><input data-item="${index}" data-item-field="quantity" value="${esc(item.quantity)}"></label></div><div class="nutrition-grid">${nutritionInput(item,index,'calories',t('kcal'))}${nutritionInput(item,index,'protein','P')}${nutritionInput(item,index,'carbs','C')}${nutritionInput(item,index,'fat','F')}</div></section>`;}
function nutritionInput(item,index,key,label){return `<label><span>${label}</span><input inputmode="decimal" data-item="${index}" data-item-field="${key}" value="${item[key]}"></label>`;}

function captureImage(index){const images=['images/oatmeal-berries.webp','images/oatmeal-berries-closeup.webp','images/chicken-buckwheat-salad.webp','images/toast-eggs-avocado.webp'];return images[index%images.length];}
function camera(){const reviewing=state.photos>0&&!state.addingAngle;const thumbs=Array.from({length:state.photos},(_,index)=>`<button class="capture-thumb ${state.selectedPhoto===index?'selected':''}" data-action="select-capture-photo" data-index="${index}" aria-label="${t('openPhoto')} ${index+1}"><img src="${captureImage(index)}" alt=""></button>`).join('');const topAction=state.addingAngle?btnIcon('back',t('back'),'cancel-angle'):btnIcon('close',t('close'),'discard-capture');const preview=reviewing?`<div class="viewfinder captured-preview"><img src="${captureImage(state.selectedPhoto)}" alt=""><button class="preview-remove" data-action="remove-photo" aria-label="${t('removePhoto')}">${icon('trash')}</button></div>`:`<div class="viewfinder"><div class="plate"><i class="food one"></i><i class="food two"></i><i class="food three"></i></div><span class="camera-hint">${t('cameraHint')}</span></div>`;const actions=reviewing?`<div class="capture-finish"><button class="primary" data-action="send-meal">${t('analyzeMeal')}</button></div>`:`<div class="camera-actions"><span class="camera-side"></span><button class="shutter" data-action="capture" aria-label="${t('takePhoto')}"></button><span class="camera-side">${state.addingAngle?state.photos+1:'1×'}</span></div>`;return shell(`<section class="camera-screen ${reviewing?'has-session':''}"><header class="camera-top">${topAction}${reviewing?`<h2>${t('reviewMeal')}</h2>`:'<span></span>'}<span></span></header>${preview}${reviewing?`<section class="capture-session"><div class="capture-thumbs">${thumbs}<button class="capture-add" data-action="add-angle" aria-label="${t('addPhoto')}">${icon('plus')}<span>${t('addPhoto')}</span></button></div><input data-bind="note" value="${esc(state.note)}" placeholder="${t('note')}"></section>`:''}${actions}</section>`,'camera');}
function review(){const count=state.photos;return shell(`<section class="screen detail">${header(`${count} ${t(count===1?'photoSaved':'photosSaved')}`,'discard-capture')}<div class="review-photo"><div class="plate"><i class="food one"></i><i class="food two"></i><i class="food three"></i></div></div><div class="thumbs">${Array.from({length:count},(_,index)=>`<button class="thumb ${state.selectedPhoto===index?'selected':''}" data-action="select-photo" data-index="${index}" aria-label="Photo ${index+1}"></button>`).join('')}<button class="add-photo" data-action="add-photo">${t('addPhoto')}</button>${count>1?`<button class="remove-thumb" data-action="remove-photo" aria-label="${t('removePhoto')}">${icon('close')}</button>`:''}</div><input class="review-note" data-bind="note" value="${esc(state.note)}" placeholder="${t('note')}"><div class="review-send"><button class="primary" data-action="send-meal">${t('send')}</button></div></section>`);}

const screens={onboarding,home,detail,settings,provider,goals,notifications,units,privacy,about,editor,camera,review};
const routeDepth={onboarding:-1,home:0,camera:1,detail:1,settings:1,provider:2,goals:2,notifications:2,units:2,privacy:2,about:2,editor:2,review:2};
function render(){app.innerHTML=(screens[state.screen]||home)();document.documentElement.lang=state.lang;state.transition='none';}
function navigationMotion(screen){const from=routeDepth[state.screen]??0;const to=routeDepth[screen]??from;return to>from?'forward':to<from?'back':'fade';}
function navigate(screen,motion=navigationMotion(screen)){state.transition=motion;state.screen=screen;state.confirm='';render();}
function toast(message,screen=state.screen){if(screen!==state.screen)state.transition=navigationMotion(screen);state.toast=message;state.screen=screen;render();window.setTimeout(()=>{state.toast='';render();},1600);}
app.addEventListener('input',event=>{const el=event.target;if(el.dataset.setup)state.setup[el.dataset.setup]=['calories','protein','carbs','fat'].includes(el.dataset.setup)?Math.max(0,Number(el.value)||0):el.value;if(el.dataset.bind==='note')state.note=el.value;if(el.dataset.bind==='correction')state.correction=el.value;if(el.dataset.bind==='answer')state.answerText=el.value;if(el.dataset.goal){state.goalDraft??={...state.goals};state.goalDraft[el.dataset.goal]=Math.max(0,Number(el.value)||0);}const meal=state.editDraft;if(meal&&el.dataset.mealField)meal[el.dataset.mealField]=el.value;if(meal&&el.dataset.itemField){const item=meal.items[Number(el.dataset.item)];if(item)item[el.dataset.itemField]=['calories','protein','carbs','fat'].includes(el.dataset.itemField)?Math.max(0,Number(el.value)||0):el.value;}});
app.addEventListener('click',event=>{
  const target=event.target.closest('[data-action]');if(!target||target.disabled)return;const action=target.dataset.action;if(action==='goals'){state.goalDraft={...state.goals};return navigate('goals');}if(screens[action])return navigate(action);
  if(action==='setup-choice'){state.setup[target.dataset.field]=target.dataset.value;return render();}if(action==='setup-back'){state.onboardingStep=Math.max(0,state.onboardingStep-1);state.transition='back';return render();}if(action==='setup-next'){if(state.onboardingStep===2)calculateTargets();state.onboardingStep=Math.min(4,state.onboardingStep+1);state.transition='forward';return render();}if(action==='finish-setup'){state.goals={calories:Number(state.setup.calories),protein:Number(state.setup.protein),carbs:Number(state.setup.carbs),fat:Number(state.setup.fat)};state.selectedProvider=state.setup.provider;if(!state.connectedProviders.includes(state.setup.provider))state.connectedProviders.push(state.setup.provider);localStorage.setItem('calodone-guide-seen','true');return navigate('home','forward');}if(action==='open-photo'){state.photoViewer=target.dataset.src;return render();}if(action==='close-photo'){state.photoViewer='';return render();}if(action==='past'){state.day=-1;state.transition='back';return render();}if(action==='today'){state.day=0;state.transition='forward';return render();}if(action==='open-meal'){state.selectedMealId=target.dataset.mealId;state.showCorrection=false;return navigate('detail');}
  if(action==='answer'){if(!state.answerText.trim())return toast(t('typeAnswer'));const meal=state.screen==='home'?state.meals.find(m=>m.question):selectedMeal();if(meal){meal.question=false;meal.status='estimated';}state.answerText='';return toast(state.lang==='ru'?'Ответ сохранён':'Answer saved');}
  if(action==='retry-analysis'){const meal=state.meals.find(item=>item.id===target.dataset.mealId);if(meal)meal.status='queued';return render();}
  if(action==='toggle-correction'){state.showCorrection=!state.showCorrection;return render();}if(action==='fix'){if(!state.correction.trim())return toast(t('typeCorrection'));const meal=selectedMeal();if(meal){meal.correction=state.correction.trim();state.correction='';state.showCorrection=false;}return toast(t('correctionApplied'));}if(action==='edit'){state.editDraft=structuredClone(selectedMeal());return navigate('editor');}
  if(action==='new-capture'){state.photos=0;state.addingAngle=false;state.selectedPhoto=0;state.note='';return navigate('camera');}if(action==='add-angle'){state.addingAngle=true;return render();}if(action==='cancel-angle'){state.addingAngle=false;return render();}if(action==='capture'){state.photos+=1;state.selectedPhoto=state.photos-1;state.addingAngle=false;return render();}if(action==='select-capture-photo'){state.selectedPhoto=Number(target.dataset.index);return render();}if(action==='discard-capture'){state.photos=0;state.addingAngle=false;state.selectedPhoto=0;state.note='';return navigate('home');}if(action==='remove-photo'){state.photos=Math.max(0,state.photos-1);state.selectedPhoto=Math.max(0,Math.min(state.selectedPhoto,state.photos-1));state.addingAngle=false;return render();}
  if(action==='send-meal'){const id=`captured-${Date.now()}`;state.meals.push({id,day:0,type:'snack',time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hourCycle:'h23'}),titleEn:'New meal',titleRu:'Новая еда',photoCount:state.photos,status:'queued',note:state.note,items:[]});state.photos=0;state.addingAngle=false;state.note='';state.day=0;return toast(t('queued'),'home');}
  if(action==='language'){state.lang=state.lang==='en'?'ru':'en';return render();}if(action==='toggle-provider-catalog'){state.showProviderCatalog=!state.showProviderCatalog;return render();}if(action==='select-provider'){state.selectedProvider=target.dataset.provider;return render();}if(action==='connect-provider'){const id=target.dataset.provider;if(!state.connectedProviders.includes(id))state.connectedProviders.push(id);state.selectedProvider=id;state.showProviderCatalog=false;return render();}if(action==='save-goals'){state.goals={...state.goalDraft};state.goalDraft=null;return toast(state.lang==='ru'?'Цели сохранены':'Goals saved','settings');}if(action==='toggle-notification'){state.notifications[target.dataset.key]=!state.notifications[target.dataset.key];return render();}if(action==='choose-unit'){state.units[target.dataset.key]=target.dataset.value;return render();}if(action==='toggle-export'){state.exportPhotos=!state.exportPhotos;return render();}
  if(action==='export-data'){const blob=new Blob([JSON.stringify({goals:state.goals,units:state.units,meals:state.meals},null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='caldone-prototype-export.json';link.click();URL.revokeObjectURL(link.href);return toast(t('exported'),'privacy');}
  if(action==='confirm-remove-photos'){state.confirm='photos';return render();}if(action==='confirm-delete-data'){state.confirm='data';return render();}if(action==='confirm-delete-meal'){state.confirm='meal';return render();}if(action==='cancel-confirm'){state.confirm='';return render();}if(action==='remove-photos'){state.meals.forEach(meal=>meal.photoCount=0);state.confirm='';return toast(t('photosRemoved'),'privacy');}if(action==='delete-data'){state.meals=[];state.confirm='';return toast(t('dataDeleted'),'home');}
  if(action==='set-meal-type'){state.editDraft.type=target.dataset.value;return render();}if(action==='add-item'){state.editDraft.items.push(makeItem('New food','Новый продукт','100 g',0,0,0,0));return render();}if(action==='remove-item'){state.editDraft.items.splice(Number(target.dataset.index),1);return render();}if(action==='save-meal'){const index=state.meals.findIndex(meal=>meal.id===state.selectedMealId);if(index>=0)state.meals[index]=state.editDraft;state.editDraft=null;return toast(t('changesSaved'),'detail');}if(action==='delete-meal'){state.meals=state.meals.filter(meal=>meal.id!==state.selectedMealId);state.editDraft=null;state.confirm='';return toast(state.lang==='ru'?'Еда удалена':'Meal deleted','home');}
});
render();
