const icon = (name) => {
  const paths = {
    settings: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>',
    camera: '<path d="M14.5 4 16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h3l1.5-3h5Z"/><circle cx="12" cy="13" r="4"/>',
    back: '<path d="m15 18-6-6 6-6"/>', next: '<path d="m9 18 6-6-6-6"/>', close: '<path d="M18 6 6 18M6 6l12 12"/>',
    sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.42 1.42m11.3 11.3 1.42 1.42M2 12h2m16 0h2M4.93 19.07l1.42-1.42m11.3-11.3 1.42-1.42"/>',
    fork: '<path d="M7 3v7m-3-7v4a3 3 0 0 0 6 0V3m-3 7v11M17 3v18m0-18c-2 2-3 5-3 8h3"/>', moon: '<path d="M20 15.2A8 8 0 1 1 8.8 4 6.2 6.2 0 0 0 20 15.2Z"/>',
  };
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.fork}</svg>`;
};

const copy = {
  en: {
    today:'Today', yesterday:'Yesterday', kcal:'kcal', kj:'kJ', protein:'Protein', carbs:'Carbs', fat:'Fat', meals:'Meals', add:'Add meal', noMeals:'No meals yet',
    question:'Question about this meal', questionText:'Was the white sauce sour cream or mayonnaise?', answer:'Type an answer', answerAction:'Answer question', needsInput:'Needs input', estimated:'Estimated', analyzing:'Analyzing', breakfast:'Breakfast', lunch:'Lunch', dinner:'Dinner', snack:'Snack',
    settings:'Settings', details:'Meal details', edit:'Edit', fix:'Fix with AI', fixPlaceholder:'Two eggs, not three…', sendCorrection:'Send correction', correctionApplied:'Correction applied', cameraHint:'Photograph the whole meal', note:'Add a note (optional)', send:'Send and leave', addPhoto:'Add photo', removePhoto:'Remove selected photo', queued:'Meal sent, analyzing in background',
    accountAi:'Account & AI', aiProvider:'AI provider', connected:'Codex · Connected', notConnected:'Not connected', providerHelp:'CaloDone uses your own AI account. Your subscription and credentials stay separate from CaloDone.', model:'Model', automatic:'Automatic', disconnect:'Disconnect', connect:'Connect Codex',
    tracking:'Tracking', goals:'Daily goals', goalsHelp:'A quiet reference only. CaloDone never grades your food.', calories:'Calories', units:'Nutrition units', metricUnits:'kcal · grams', notifications:'Notifications', questionsFailures:'Questions and failures', save:'Save', appSection:'App', language:'Language', dataPrivacy:'Data & privacy', savedPhotos:'Photos kept with meals', about:'About CaloDone', version:'Version 1.2.0',
    notificationHelp:'Choose when CaloDone is allowed to interrupt you.', clarificationNotifications:'Meal questions', clarificationNotificationsHelp:'When an answer could materially change the estimate', failedNotifications:'Failed analysis', failedNotificationsHelp:'When a meal could not be processed', readyNotifications:'Meal ready', readyNotificationsHelp:'After every successful analysis', reminderNotifications:'Daily reminder', reminderNotificationsHelp:'A quiet prompt if no meals were logged', done:'Done',
    energy:'Energy', portionWeight:'Portion weight', grams:'Grams', ounces:'Ounces', unitHelp:'These units change how nutrition is displayed. Stored values keep their precision.', privacyHelp:'Meal photos stay in private app storage and never enter the system gallery.', photoStorage:'Meal photos', privateStorage:'Saved with each meal', systemGallery:'System gallery', never:'Never', includeExport:'Include photos in export', exportData:'Export my data', removePhotos:'Remove all saved photos', deleteData:'Delete all meal data', confirmRemovePhotos:'Remove photos from every meal?', confirmDeleteData:'Delete every meal and photo?', cancel:'Cancel', delete:'Delete', exported:'Mock export downloaded', photosRemoved:'Saved photos removed', dataDeleted:'Meal data deleted',
    aboutBody:'A quiet calorie tracker for people who do not want tracking to become another job.', openSource:'Open source prototype', license:'Prototype UI · MIT licensed project', editMeal:'Edit meal', mealType:'Meal type', title:'Title', time:'Time', items:'Items', itemName:'Food', quantity:'Quantity', addItem:'Add item', saveChanges:'Save changes', deleteMeal:'Delete meal', confirmDeleteMeal:'Delete this meal?', changesSaved:'Meal updated', mealPhotos:'Meal photos', photoSaved:'saved photo', photosSaved:'saved photos', back:'Back', takePhoto:'Take photo', previousDay:'Previous day', nextDay:'Next day', close:'Close', typeAnswer:'Type an answer first', typeCorrection:'Describe the correction first'
  },
  ru: {
    today:'Сегодня', yesterday:'Вчера', kcal:'ккал', kj:'кДж', protein:'Белки', carbs:'Углеводы', fat:'Жиры', meals:'Приёмы пищи', add:'Добавить еду', noMeals:'Пока ничего нет', question:'Вопрос об этой еде', questionText:'Белый соус — сметана или майонез?', answer:'Написать ответ', answerAction:'Ответить на вопрос', needsInput:'Нужен ответ', estimated:'Оценено', analyzing:'Анализируем', breakfast:'Завтрак', lunch:'Обед', dinner:'Ужин', snack:'Перекус',
    settings:'Настройки', details:'Приём пищи', edit:'Изменить', fix:'Исправить с ИИ', fixPlaceholder:'Два яйца, не три…', sendCorrection:'Отправить исправление', correctionApplied:'Исправление применено', cameraHint:'Снимите весь приём пищи', note:'Добавить заметку (необязательно)', send:'Отправить и уйти', addPhoto:'Ещё фото', removePhoto:'Удалить выбранное фото', queued:'Еда отправлена, анализируем в фоне',
    accountAi:'Аккаунт и ИИ', aiProvider:'ИИ-провайдер', connected:'Codex · Подключён', notConnected:'Не подключён', providerHelp:'CaloDone использует ваш ИИ-аккаунт. Подписка и данные входа отделены от CaloDone.', model:'Модель', automatic:'Автоматически', disconnect:'Отключить', connect:'Подключить Codex', tracking:'Отслеживание', goals:'Дневные цели', goalsHelp:'Только спокойный ориентир. CaloDone не оценивает вашу еду.', calories:'Калории', units:'Единицы измерения', metricUnits:'ккал · граммы', notifications:'Уведомления', questionsFailures:'Вопросы и ошибки', save:'Сохранить', appSection:'Приложение', language:'Язык', dataPrivacy:'Данные и приватность', savedPhotos:'Фото хранятся вместе с едой', about:'О CaloDone', version:'Версия 1.2.0',
    notificationHelp:'Выберите, когда CaloDone может вас отвлекать.', clarificationNotifications:'Вопросы о еде', clarificationNotificationsHelp:'Когда ответ может заметно изменить оценку', failedNotifications:'Ошибка анализа', failedNotificationsHelp:'Если еду не удалось обработать', readyNotifications:'Еда готова', readyNotificationsHelp:'После каждого успешного анализа', reminderNotifications:'Ежедневное напоминание', reminderNotificationsHelp:'Если за день ничего не добавлено', done:'Готово',
    energy:'Энергия', portionWeight:'Вес порций', grams:'Граммы', ounces:'Унции', unitHelp:'Единицы меняют только отображение. Сохранённые значения не теряют точность.', privacyHelp:'Фото еды хранятся внутри приложения и не попадают в системную галерею.', photoStorage:'Фотографии еды', privateStorage:'Сохранены вместе с едой', systemGallery:'Системная галерея', never:'Никогда', includeExport:'Добавлять фото в экспорт', exportData:'Экспортировать мои данные', removePhotos:'Удалить все сохранённые фото', deleteData:'Удалить всю историю еды', confirmRemovePhotos:'Удалить фотографии из всех приёмов пищи?', confirmDeleteData:'Удалить всю еду и фотографии?', cancel:'Отмена', delete:'Удалить', exported:'Тестовый экспорт скачан', photosRemoved:'Сохранённые фото удалены', dataDeleted:'История еды удалена',
    aboutBody:'Спокойный счётчик калорий для тех, кто не хочет превращать учёт еды в отдельную работу.', openSource:'Открытый прототип', license:'Прототип интерфейса · проект MIT', editMeal:'Изменить еду', mealType:'Тип еды', title:'Название', time:'Время', items:'Состав', itemName:'Продукт', quantity:'Количество', addItem:'Добавить продукт', saveChanges:'Сохранить изменения', deleteMeal:'Удалить приём пищи', confirmDeleteMeal:'Удалить этот приём пищи?', changesSaved:'Еда обновлена', mealPhotos:'Фотографии еды', photoSaved:'сохранённое фото', photosSaved:'сохранённых фото', back:'Назад', takePhoto:'Сделать фото', previousDay:'Предыдущий день', nextDay:'Следующий день', close:'Закрыть', typeAnswer:'Сначала напишите ответ', typeCorrection:'Сначала опишите исправление'
  }
};

const makeItem=(nameEn,nameRu,quantity,calories,protein,carbs,fat)=>({nameEn,nameRu,quantity,calories,protein,carbs,fat});
const initialMeals=[
  {id:'breakfast',day:0,type:'breakfast',time:'08:20',titleEn:'Oatmeal with berries',titleRu:'Овсянка с ягодами',photoCount:1,status:'estimated',items:[makeItem('Oatmeal','Овсянка','220 g',280,10,48,6),makeItem('Blueberries','Черника','70 g',40,1,9,0),makeItem('Yogurt','Йогурт','120 g',118,8,12,4)]},
  {id:'lunch',day:0,type:'lunch',time:'13:05',titleEn:'Chicken, buckwheat & salad',titleRu:'Курица с гречкой и салатом',photoCount:1,status:'needs_input',question:true,items:[makeItem('Chicken breast','Куриная грудка','170 g',280,38,0,12),makeItem('Buckwheat','Гречка','180 g',198,7,38,2),makeItem('Cucumber salad','Салат из огурцов','150 g',74,2,8,4),makeItem('Sour cream','Сметана','30 g',60,1,2,5)]},
  {id:'dinner',day:0,type:'dinner',time:'19:18',titleEn:'Toast, eggs & avocado',titleRu:'Тост, яйца и авокадо',photoCount:2,status:'estimated',items:[makeItem('Eggs','Яйца','2',144,13,1,10),makeItem('Toast','Тост','1 slice',72,3,13,1),makeItem('Avocado','Авокадо','40 g',60,1,3,5)]},
  {id:'past-lunch',day:-1,type:'lunch',time:'12:44',titleEn:'Tomato pasta',titleRu:'Паста с томатами',photoCount:1,status:'estimated',items:[makeItem('Pasta','Паста','280 g',510,16,82,12)]},
  {id:'past-dinner',day:-1,type:'dinner',time:'20:03',titleEn:'Cottage cheese & apple',titleRu:'Творог и яблоко',photoCount:1,status:'estimated',items:[makeItem('Cottage cheese','Творог','200 g',242,32,7,9),makeItem('Apple','Яблоко','1',80,0,21,0)]}
];

const state={screen:'home',lang:'en',toast:'',day:0,selectedMealId:'lunch',photos:0,selectedPhoto:0,note:'',connected:true,units:{energy:'kcal',weight:'g'},goals:{calories:2000,protein:120,carbs:220,fat:65},goalDraft:null,editDraft:null,exportPhotos:true,notifications:{questions:true,failed:true,ready:false,reminder:false},meals:structuredClone(initialMeals),confirm:'',correction:'',answerText:''};
const t=key=>copy[state.lang][key]??key;
const app=document.querySelector('#app');
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const energy=kcal=>state.units.energy==='kj'?Math.round(kcal*4.184):Math.round(kcal);
const energyUnit=()=>t(state.units.energy==='kj'?'kj':'kcal');
const itemName=item=>item.customName??(state.lang==='ru'?item.nameRu:item.nameEn);
const mealTitle=meal=>meal.customTitle??(state.lang==='ru'?meal.titleRu:meal.titleEn);
const totals=meal=>meal.items.reduce((sum,item)=>({calories:sum.calories+Number(item.calories),protein:sum.protein+Number(item.protein),carbs:sum.carbs+Number(item.carbs),fat:sum.fat+Number(item.fat)}),{calories:0,protein:0,carbs:0,fat:0});
const selectedMeal=()=>state.meals.find(meal=>meal.id===state.selectedMealId);
function shell(content,extra=''){return `<div class="device ${extra}">${content}${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}</div>`;}
function btnIcon(name,label,action,disabled=false){return `<button class="icon-btn" aria-label="${esc(label)}" data-action="${action}" ${disabled?'disabled':''}>${icon(name)}</button>`;}
function foodPlate(){return '<i class="tiny-plate"><i class="tiny-food one"></i><i class="tiny-food two"></i><i class="tiny-food three"></i></i>';}
function header(title,back,action=''){return `<header class="header">${btnIcon('back',t('back'),back)}<h2>${esc(title)}</h2>${action||'<span></span>'}</header>`;}

function home(){
  const meals=state.meals.filter(meal=>meal.day===state.day);const sum=meals.reduce((total,meal)=>{const value=totals(meal);Object.keys(total).forEach(k=>total[k]+=value[k]);return total;},{calories:0,protein:0,carbs:0,fat:0});const questionMeal=meals.find(meal=>meal.question);const dayTitle=state.day===0?t('today'):t('yesterday');
  return shell(`<section class="screen"><header class="topbar"><div><p class="eyebrow">CaloDone</p><div class="day-nav">${btnIcon('back',t('previousDay'),'past',state.day<0)}<h1>${dayTitle}</h1>${btnIcon('next',t('nextDay'),'today',state.day===0)}</div></div>${btnIcon('settings',t('settings'),'settings')}</header><section class="summary"><p class="calories">${energy(sum.calories).toLocaleString()} / ${energy(state.goals.calories).toLocaleString()} <span class="unit">${energyUnit()}</span></p><div class="track"><span style="width:${Math.min(100,sum.calories/state.goals.calories*100)}%"></span></div><div class="macro-row">${macro(sum.protein,state.goals.protein,t('protein'))}${macro(sum.carbs,state.goals.carbs,t('carbs'))}${macro(sum.fat,state.goals.fat,t('fat'))}</div></section>${questionMeal?clarification(questionMeal,true):''}<div class="row section-title"><h2>${t('meals')}</h2><span class="count">${meals.length}</span></div><div class="meal-list">${meals.length?meals.map(mealRow).join(''):`<p class="empty-line">${t('noMeals')}</p>`}</div><div class="capture-dock"><button class="primary" data-action="new-capture">${icon('camera')} ${t('add')}</button></div></section>`);
}
function macro(value,goal,label){const shown=state.units.weight==='oz'?(value/28.35).toFixed(1):Math.round(value);const goalShown=state.units.weight==='oz'?(goal/28.35).toFixed(1):goal;return `<div class="macro"><strong>${shown} / ${goalShown} ${state.units.weight==='oz'?'oz':'g'}</strong><small>${label}</small></div>`;}
function clarification(meal,withLink){return `<section class="question">${withLink?`<button class="question-meal" data-action="open-meal" data-meal-id="${meal.id}"><span class="mini-photo">${foodPlate()}</span><span><strong>${t(meal.type)}</strong><small>${meal.time} · ${energy(totals(meal).calories)} ${energyUnit()}</small></span><b aria-hidden="true">›</b></button>`:''}<p class="question-label">✦ ${t('question')}</p><p class="question-text">${t('questionText')}</p><div class="composer"><input data-bind="answer" value="${esc(state.answerText)}" placeholder="${t('answer')}"/><button class="send-circle" data-action="answer" aria-label="${t('answerAction')}">↑</button></div></section>`;}
function mealRow(meal){const total=totals(meal);return `<button class="meal" data-action="open-meal" data-meal-id="${meal.id}"><span class="meal-icon">${icon(meal.type==='breakfast'?'sun':meal.type==='dinner'?'moon':'fork')}</span><span class="meal-copy"><span class="meal-head"><span class="meal-title">${esc(mealTitle(meal))}</span><span class="meal-kcal">${energy(total.calories)} ${energyUnit()}</span></span><span class="meal-meta"><span>${meal.time}</span><span class="status">${meal.status==='needs_input'?'<i class="dot"></i>'+t('needsInput'):meal.status==='queued'?'<i class="dot"></i>'+t('analyzing'):t('estimated')}</span></span><span class="meal-items">${esc(meal.items.map(itemName).join(', '))}</span></span></button>`;}

function detail(){
  const meal=selectedMeal();if(!meal)return home();const total=totals(meal);
  if(meal.status==='queued')return shell(`<section class="screen detail">${header(t('details'),'home')}<p class="meal-type">${t(meal.type)} · ${meal.time}</p><h1 class="detail-title">${esc(mealTitle(meal))}</h1>${photoBlock(meal)}<section class="processing"><i class="dot"></i><strong>${t('analyzing')}</strong><p>${esc(meal.note)}</p></section></section>`);
  return shell(`<section class="screen detail">${header(t('details'),'home',`<button class="header-action" data-action="edit">${t('edit')}</button>`)}<p class="meal-type">${t(meal.type)} · ${meal.time}</p><h1 class="detail-title">${esc(mealTitle(meal))}</h1>${photoBlock(meal)}${meal.question?clarification(meal,false):''}<div class="detail-total"><strong>${energy(total.calories)} ${energyUnit()}</strong><span>P ${Math.round(total.protein)} · C ${Math.round(total.carbs)} · F ${Math.round(total.fat)}</span></div><div>${meal.items.map(item=>`<div class="food-row"><div><strong>${esc(itemName(item))}</strong><small>${esc(item.quantity)}</small></div><div class="food-nutrition"><strong>${energy(item.calories)} ${energyUnit()}</strong><small>P ${item.protein} · C ${item.carbs} · F ${item.fat}</small></div></div>`).join('')}</div>${meal.correction?`<p class="applied-correction">✓ ${t('correctionApplied')}: ${esc(meal.correction)}</p>`:''}<section class="ai-fix"><p class="ai-label">✦ ${t('fix')}</p><div class="composer"><input data-bind="correction" value="${esc(state.correction)}" placeholder="${t('fixPlaceholder')}"/><button class="send-circle" data-action="fix" aria-label="${t('sendCorrection')}">↑</button></div></section></section>`);
}
function photoBlock(meal){if(!meal.photoCount)return '';const label=`${meal.photoCount} ${t(meal.photoCount===1?'photoSaved':'photosSaved')}`;return `<section class="saved-photos" aria-label="${t('mealPhotos')}"><div class="saved-photo">${foodPlate()}<span>${label}</span></div></section>`;}

function settings(){return shell(`<section class="screen settings">${header(t('settings'),'home')}${settingsSection(t('accountAi'),settingsLink(t('aiProvider'),state.connected?t('connected'):t('notConnected'),'provider'))}${settingsSection(t('tracking'),settingsLink(t('goals'),`${state.goals.calories} ${t('kcal')}`,'goals')+settingsLink(t('units'),`${energyUnit()} · ${state.units.weight==='oz'?t('ounces').toLowerCase():t('grams').toLowerCase()}`,'units')+settingsLink(t('notifications'),t('questionsFailures'),'notifications'))}${settingsSection(t('appSection'),settingsLink(t('language'),state.lang==='en'?'English':'Русский','language')+settingsLink(t('dataPrivacy'),t('savedPhotos'),'privacy')+settingsLink(t('about'),t('version'),'about'))}</section>`);}
function settingsSection(title,content){return `<section class="settings-section"><h3>${title}</h3><div class="settings-panel">${content}</div></section>`;}
function settingsLink(label,value,action){return `<button class="settings-link" data-action="${action}"><span><strong>${label}</strong><small>${value}</small></span><b aria-hidden="true">›</b></button>`;}
function infoRow(label,value){return `<div class="info-row"><span>${label}</span><strong>${value}</strong></div>`;}
function provider(){return shell(`<section class="screen settings">${header(t('aiProvider'),'settings')}<p class="settings-copy detail-copy">${t('providerHelp')}</p><div class="settings-panel">${infoRow(t('aiProvider'),state.connected?t('connected'):t('notConnected'))}${infoRow(t('model'),t('automatic'))}</div><div class="settings-primary"><button class="primary ${state.connected?'danger-secondary':''}" data-action="toggle-provider">${state.connected?t('disconnect'):t('connect')}</button></div></section>`);}
function goals(){return shell(`<section class="screen settings">${header(t('goals'),'settings')}<p class="settings-copy detail-copy">${t('goalsHelp')}</p><div class="settings-panel goal-panel">${goalField('calories',t('calories'),t('kcal'))}${goalField('protein',t('protein'),'g')}${goalField('carbs',t('carbs'),'g')}${goalField('fat',t('fat'),'g')}</div><div class="settings-primary"><button class="primary" data-action="save-goals">${t('save')}</button></div></section>`);}
function goalField(key,label,unit){const values=state.goalDraft??state.goals;return `<label class="setting-row"><span>${label}</span><span class="number-input"><input inputmode="decimal" data-goal="${key}" value="${values[key]}"><b>${unit}</b></span></label>`;}
function notifications(){return shell(`<section class="screen settings">${header(t('notifications'),'settings')}<p class="settings-copy detail-copy">${t('notificationHelp')}</p><div class="settings-panel notification-panel">${toggleSetting('questions',t('clarificationNotifications'),t('clarificationNotificationsHelp'))}${toggleSetting('failed',t('failedNotifications'),t('failedNotificationsHelp'))}${toggleSetting('ready',t('readyNotifications'),t('readyNotificationsHelp'))}${toggleSetting('reminder',t('reminderNotifications'),t('reminderNotificationsHelp'))}</div><button class="text-action" data-action="settings">${t('done')}</button></section>`);}
function toggleSetting(key,label,help){const checked=state.notifications[key];return `<div class="toggle-row"><span><strong>${label}</strong><small>${help}</small></span><button class="toggle ${checked?'checked':''}" role="switch" aria-checked="${checked}" aria-label="${label}" data-action="toggle-notification" data-key="${key}"><i></i></button></div>`;}
function units(){return shell(`<section class="screen settings">${header(t('units'),'settings')}<p class="settings-copy detail-copy">${t('unitHelp')}</p>${choiceGroup(t('energy'),'energy',[['kcal',t('kcal')],['kj',t('kj')]],state.units.energy)}${choiceGroup(t('portionWeight'),'weight',[['g',t('grams')],['oz',t('ounces')]],state.units.weight)}</section>`);}
function choiceGroup(title,key,options,current){return `<section class="choice-section"><h3>${title}</h3><div class="choice-control">${options.map(([value,label])=>`<button data-action="choose-unit" data-key="${key}" data-value="${value}" class="${current===value?'selected':''}" aria-pressed="${current===value}">${label}</button>`).join('')}</div></section>`;}
function privacy(){return shell(`<section class="screen settings">${header(t('dataPrivacy'),'settings')}<p class="settings-copy detail-copy">${t('privacyHelp')}</p><div class="settings-panel">${infoRow(t('photoStorage'),t('privateStorage'))}${infoRow(t('systemGallery'),t('never'))}<div class="toggle-row privacy-toggle"><span><strong>${t('includeExport')}</strong></span><button class="toggle ${state.exportPhotos?'checked':''}" role="switch" aria-checked="${state.exportPhotos}" aria-label="${t('includeExport')}" data-action="toggle-export"><i></i></button></div></div><div class="action-list"><button data-action="export-data">${t('exportData')}</button><button data-action="confirm-remove-photos">${t('removePhotos')}</button><button class="danger-text" data-action="confirm-delete-data">${t('deleteData')}</button></div>${confirmPanel()}</section>`);}
function confirmPanel(){if(!state.confirm)return '';const removing=state.confirm==='photos';return `<section class="confirm-panel"><strong>${t(removing?'confirmRemovePhotos':'confirmDeleteData')}</strong><div><button data-action="cancel-confirm">${t('cancel')}</button><button class="danger-fill" data-action="${removing?'remove-photos':'delete-data'}">${t('delete')}</button></div></section>`;}
function about(){return shell(`<section class="screen settings">${header(t('about'),'settings')}<div class="about-mark">C</div><h1 class="about-title">CaloDone</h1><p class="about-copy">${t('aboutBody')}</p><div class="settings-panel about-info">${infoRow(t('version'),'1.2.0')}${infoRow(t('openSource'),'CaloDone')}${infoRow('License','MIT')}</div><p class="about-foot">${t('license')}</p></section>`);}

function editor(){const meal=state.editDraft;if(!meal)return detail();return shell(`<section class="screen settings editor">${header(t('editMeal'),'detail')}<label class="editor-field"><span>${t('mealType')}</span><div class="type-chips">${['breakfast','lunch','dinner','snack'].map(type=>`<button data-action="set-meal-type" data-value="${type}" class="${meal.type===type?'selected':''}">${t(type)}</button>`).join('')}</div></label><div class="editor-top"><label class="editor-field"><span>${t('title')}</span><input data-meal-field="customTitle" value="${esc(mealTitle(meal))}"></label><label class="editor-field compact"><span>${t('time')}</span><input data-meal-field="time" value="${meal.time}"></label></div><h3 class="editor-heading">${t('items')}</h3><div class="editor-items">${meal.items.map((item,index)=>editorItem(item,index,meal.items.length>1)).join('')}</div><button class="add-item" data-action="add-item">＋ ${t('addItem')}</button><div class="settings-primary"><button class="primary" data-action="save-meal">${t('saveChanges')}</button></div><button class="text-action danger-text" data-action="confirm-delete-meal">${t('deleteMeal')}</button>${state.confirm==='meal'?`<section class="confirm-panel"><strong>${t('confirmDeleteMeal')}</strong><div><button data-action="cancel-confirm">${t('cancel')}</button><button class="danger-fill" data-action="delete-meal">${t('delete')}</button></div></section>`:''}</section>`);}
function editorItem(item,index,canRemove){return `<section class="item-editor"><div class="item-editor-head"><strong>${index+1}</strong>${canRemove?`<button aria-label="Remove item" data-action="remove-item" data-index="${index}">×</button>`:''}</div><div class="editor-top"><label class="editor-field"><span>${t('itemName')}</span><input data-item="${index}" data-item-field="customName" value="${esc(itemName(item))}"></label><label class="editor-field compact"><span>${t('quantity')}</span><input data-item="${index}" data-item-field="quantity" value="${esc(item.quantity)}"></label></div><div class="nutrition-grid">${nutritionInput(item,index,'calories',t('kcal'))}${nutritionInput(item,index,'protein','P')}${nutritionInput(item,index,'carbs','C')}${nutritionInput(item,index,'fat','F')}</div></section>`;}
function nutritionInput(item,index,key,label){return `<label><span>${label}</span><input inputmode="decimal" data-item="${index}" data-item-field="${key}" value="${item[key]}"></label>`;}

function camera(){return shell(`<section class="camera-screen"><header class="camera-top">${btnIcon('close',t('close'),'close-camera')}<span></span></header><div class="viewfinder"><div class="plate"><i class="food one"></i><i class="food two"></i><i class="food three"></i></div><span class="camera-hint">${t('cameraHint')}</span></div><div class="camera-actions"><span class="camera-side"></span><button class="shutter" data-action="capture" aria-label="${t('takePhoto')}"></button><span class="camera-side">1×</span></div></section>`,'camera');}
function review(){const count=state.photos;return shell(`<section class="screen detail">${header(`${count} ${t(count===1?'photoSaved':'photosSaved')}`,'discard-capture')}<div class="review-photo"><div class="plate"><i class="food one"></i><i class="food two"></i><i class="food three"></i></div></div><div class="thumbs">${Array.from({length:count},(_,index)=>`<button class="thumb ${state.selectedPhoto===index?'selected':''}" data-action="select-photo" data-index="${index}" aria-label="Photo ${index+1}"></button>`).join('')}<button class="add-photo" data-action="add-photo" ${count>=4?'disabled':''}>${t('addPhoto')}</button>${count>1?`<button class="remove-thumb" data-action="remove-photo" aria-label="${t('removePhoto')}">×</button>`:''}</div><input class="review-note" data-bind="note" value="${esc(state.note)}" placeholder="${t('note')}"><div class="review-send"><button class="primary" data-action="send-meal">${t('send')} ↑</button></div></section>`);}

const screens={home,detail,settings,provider,goals,notifications,units,privacy,about,editor,camera,review};
function render(){app.innerHTML=(screens[state.screen]||home)();document.documentElement.lang=state.lang;}
function navigate(screen){state.screen=screen;state.confirm='';render();}
function toast(message,screen=state.screen){state.toast=message;state.screen=screen;render();window.setTimeout(()=>{state.toast='';render();},1600);}
app.addEventListener('input',event=>{const el=event.target;if(el.dataset.bind==='note')state.note=el.value;if(el.dataset.bind==='correction')state.correction=el.value;if(el.dataset.bind==='answer')state.answerText=el.value;if(el.dataset.goal){state.goalDraft??={...state.goals};state.goalDraft[el.dataset.goal]=Math.max(0,Number(el.value)||0);}const meal=state.editDraft;if(meal&&el.dataset.mealField)meal[el.dataset.mealField]=el.value;if(meal&&el.dataset.itemField){const item=meal.items[Number(el.dataset.item)];if(item)item[el.dataset.itemField]=['calories','protein','carbs','fat'].includes(el.dataset.itemField)?Math.max(0,Number(el.value)||0):el.value;}});
app.addEventListener('click',event=>{
  const target=event.target.closest('[data-action]');if(!target||target.disabled)return;const action=target.dataset.action;if(action==='goals'){state.goalDraft={...state.goals};return navigate('goals');}if(screens[action])return navigate(action);
  if(action==='past'){state.day=-1;return render();}if(action==='today'){state.day=0;return render();}if(action==='open-meal'){state.selectedMealId=target.dataset.mealId;return navigate('detail');}
  if(action==='answer'){if(!state.answerText.trim())return toast(t('typeAnswer'));const meal=state.screen==='home'?state.meals.find(m=>m.question):selectedMeal();if(meal){meal.question=false;meal.status='estimated';}state.answerText='';return toast(state.lang==='ru'?'Ответ сохранён':'Answer saved');}
  if(action==='fix'){if(!state.correction.trim())return toast(t('typeCorrection'));const meal=selectedMeal();if(meal){meal.correction=state.correction.trim();state.correction='';}return toast(t('correctionApplied'));}if(action==='edit'){state.editDraft=structuredClone(selectedMeal());return navigate('editor');}
  if(action==='new-capture'){state.photos=0;state.note='';return navigate('camera');}if(action==='add-photo')return navigate('camera');if(action==='close-camera')return navigate(state.photos?'review':'home');if(action==='capture'){state.photos=Math.min(4,state.photos+1);state.selectedPhoto=state.photos-1;return navigate('review');}if(action==='discard-capture'){state.photos=0;state.note='';return navigate('home');}if(action==='select-photo'){state.selectedPhoto=Number(target.dataset.index);return render();}if(action==='remove-photo'){state.photos--;state.selectedPhoto=Math.max(0,Math.min(state.selectedPhoto,state.photos-1));return state.photos?render():navigate('camera');}
  if(action==='send-meal'){const id=`captured-${Date.now()}`;state.meals.push({id,day:0,type:'snack',time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),titleEn:'Meal being analyzed',titleRu:'Анализируем еду',photoCount:state.photos,status:'queued',note:state.note,items:[]});state.photos=0;state.note='';state.day=0;return toast(t('queued'),'home');}
  if(action==='language'){state.lang=state.lang==='en'?'ru':'en';return render();}if(action==='toggle-provider'){state.connected=!state.connected;return toast(state.connected?t('connected'):t('notConnected'),'provider');}if(action==='save-goals'){state.goals={...state.goalDraft};state.goalDraft=null;return toast(state.lang==='ru'?'Цели сохранены':'Goals saved','settings');}if(action==='toggle-notification'){state.notifications[target.dataset.key]=!state.notifications[target.dataset.key];return render();}if(action==='choose-unit'){state.units[target.dataset.key]=target.dataset.value;return render();}if(action==='toggle-export'){state.exportPhotos=!state.exportPhotos;return render();}
  if(action==='export-data'){const blob=new Blob([JSON.stringify({goals:state.goals,units:state.units,meals:state.meals},null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='calodone-prototype-export.json';link.click();URL.revokeObjectURL(link.href);return toast(t('exported'),'privacy');}
  if(action==='confirm-remove-photos'){state.confirm='photos';return render();}if(action==='confirm-delete-data'){state.confirm='data';return render();}if(action==='confirm-delete-meal'){state.confirm='meal';return render();}if(action==='cancel-confirm'){state.confirm='';return render();}if(action==='remove-photos'){state.meals.forEach(meal=>meal.photoCount=0);state.confirm='';return toast(t('photosRemoved'),'privacy');}if(action==='delete-data'){state.meals=[];state.confirm='';return toast(t('dataDeleted'),'home');}
  if(action==='set-meal-type'){state.editDraft.type=target.dataset.value;return render();}if(action==='add-item'){state.editDraft.items.push(makeItem('New food','Новый продукт','100 g',0,0,0,0));return render();}if(action==='remove-item'){state.editDraft.items.splice(Number(target.dataset.index),1);return render();}if(action==='save-meal'){const index=state.meals.findIndex(meal=>meal.id===state.selectedMealId);if(index>=0)state.meals[index]=state.editDraft;state.editDraft=null;return toast(t('changesSaved'),'detail');}if(action==='delete-meal'){state.meals=state.meals.filter(meal=>meal.id!==state.selectedMealId);state.editDraft=null;state.confirm='';return toast(state.lang==='ru'?'Еда удалена':'Meal deleted','home');}
});
render();
